server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-board?rewriteBatchedStatements=true
    username: root
    password: 602057
  servlet:
    multipart:
      max-file-size: 500MB
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
logging:
  level:
    com.maruhxn.boardserver: debug
    org.hibernate.SQL: debug

file:
  upload_dir: C:/Users/asus/project/spring-board/board-server/upload/